imx8mp.dtsi: Correct wrong references to power/clock
barebox/barebox pull request #17
Opened 2022-10-16 13:15 UTC by hcl-dr

Imported kernel tree for IMX8MP contains the following errors:

For the IMX8MP the power-domain references does not refer to an _actual_ power domain. This breaks USB as probe call will fail. The correct power domain is pgc_hsiomix.

Flexspi clocks misnamed as "qspi" and "qspi_en" leading to probe error. The Flexspi driver uses clock names "fspi" and "fspi_en" as is the case for all IMX8 familiy members employing this IP block.

Signed-off-by: Hans Christian Lonstad <hcl@datarespons.com>

2022-10-16 16:45 UTC, a3f requested changes

2022-10-16 16:45 UTC, a3f commented on arch/arm/dts/imx8mp.dtsi
> +	clock-names = "fspi_en", "fspi";
But that seems to be already the current setting?

https://github.com/saschahauer/barebox/blob/6c17dd42db026ff7aee6e04d95bb440e120bb052/dts/src/arm64/freescale/imx8mp.dtsi#L947

2022-10-16 16:45 UTC, a3f commented on arch/arm/dts/imx8mp.dtsi
> +	power-domains = <&pgc_hsiomix>;
I assume there's a reason there's a dedicated device for power sequencing (`blk-ctrl@32f10000`) instead of directly referencing just this single power domain. Will have to ask @lynxeye-dev about it tomorrow. Does USB work if you just delete the power-domains property?

We ran into this same issue with i.MX8MM/i.MX8MN too, there we used `barebox,allow-dummy` in the original power domain node at first to maintain working order and after GPCv2 driver update, they could be removed again.

2022-10-16 16:51 UTC, lynxeye-dev commented on arch/arm/dts/imx8mp.dtsi
> +	power-domains = <&pgc_hsiomix>;
Yes, the blk-ctrls make sure the right power up/down sequence is used. Without the blk-ctrl there is no guarantee that the ADB is powered up correctly and peripherals in the HSIO domain might not be able to access the system bus. So if the power domain isn't already enabled by the TF-A or something running before Barebox, the right solution is to port over the blk-ctrl driver, instead of changing the DT.

2022-10-17 06:29 UTC, hcl-dr commented
I can see the flexspi clock is handled in master ...

Regarding the power domain issue, I assume removing the reference from the USB/PHY instances would work as probing and hence failing with be left out.
Agree that correct dependency order should be maintained, but code would somehow require handling of indirect dependencies. As it looks in v2022.10.0 matching is performed against non-suppliers of power domains.
Dropping the PR waiting for the underlying issue to be resolved then.


> 16. okt. 2022 kl. 18:45 skrev Ahmad Fatoum ***@***.***>:
> 
> 
> @a3f requested changes on this pull request.
> 
> In arch/arm/dts/imx8mp.dtsi:
> 
> > @@ -7,3 +7,23 @@
>  		syscon = <&src>;
>  	};
>  };
> +
> +&flexspi {
> +	clock-names = "fspi_en", "fspi";
> 
> But that seems to be already the current setting?
> 
> https://github.com/saschahauer/barebox/blob/6c17dd42db026ff7aee6e04d95bb440e120bb052/dts/src/arm64/freescale/imx8mp.dtsi#L947
> 
> In arch/arm/dts/imx8mp.dtsi:
> 
> > @@ -7,3 +7,23 @@
>  		syscon = <&src>;
>  	};
>  };
> +
> +&flexspi {
> +	clock-names = "fspi_en", "fspi";
> +};
> +
> +&usb3_0 {
> +	power-domains = <&pgc_hsiomix>;
> 
> I assume there's a reason there's a dedicated device for power sequencing ***@***.***) instead of directly referencing just this single power domain. Will have to ask @lynxeye-dev about it tomorrow. Does USB work if you just delete the power-domains property?
> 
> We ran into this same issue with i.MX8MM/i.MX8MN too, there we used barebox,allow-dummy in the original power domain node at first to maintain working order and after GPCv2 driver update, they could be removed again.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

2022-10-17 06:37 UTC, hcl-dr commented
flexspi clock issue invalid, removing PR

2022-10-17 06:37 UTC, closed without merging

2022-10-17 10:55 UTC, a3f commented
> Regarding the power domain issue, I assume removing the reference from the USB/PHY instances would work as probing and hence failing with be left out.

If this is a regression and USB used to work before the device tree update, as
TF-A set it up like mentioned by @lynxeye-dev, we can add

```
&hsio_blk_ctrl {
	barebox,allow-dummy;
};
```

to maintain old behavior until we have a proper driver. Can you try this out?

> Agree that correct dependency order should be maintained, but code would somehow require handling of indirect dependencies. As it looks in v2022.10.0 matching is performed against non-suppliers of power domains.

I am not sure what you mean here. If barebox had a blk-ctrl power domain driver, it would toggle that it in turn would tickle resets/power domains.

2022-10-17 11:38 UTC, hcl-dr commented
Your suggested method applies if a platform driver for the board exists and is enabled for deep probe.
We have three custom variants built on IMX8MP Quadlite (which also has some specific issues missing some IP blocks)
I will switch the boards to using platform drivers.

If the platform driver is not configured for deep probe,  of_device_ensure_probed() returns zero and the dummy quirk is not considered.
Missing this, matching is performed against the hsio_blk_ctrl which does not provide any power domain as for now.
> 17. okt. 2022 kl. 12:55 skrev Ahmad Fatoum ***@***.***>:
> 
> 
> Regarding the power domain issue, I assume removing the reference from the USB/PHY instances would work as probing and hence failing with be left out.
> 
> If this is a regression and USB used to work before the device tree update, as
> TF-A set it up like mentioned by @lynxeye-dev, we can add
> 
> &hsio_blk_ctrl {
> 	barebox,allow-dummy;
> };
> 
> to maintain old behavior until we have a proper driver. Can you try this out?
> 
> Agree that correct dependency order should be maintained, but code would somehow require handling of indirect dependencies. As it looks in v2022.10.0 matching is performed against non-suppliers of power domains.
> 
> I am not sure what you mean here. If barebox had a blk-ctrl power domain driver, it would toggle that it in turn would tickle resets/power domains.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.
>

2022-10-17 13:52 UTC, a3f commented
> Your suggested method applies if a platform driver for the board exists and is enabled for deep probe.

Yes. It's not worth it anymore to do driver core changes for non-deep-probe enabled systems.

> We have three custom variants built on IMX8MP Quadlite (which also has some specific issues missing some IP blocks)

I ran into these issues as well with i.MX8MMQuadLite. There's barebox infrastructure to handle that now, see
the series  I just sent out.

> I will switch the boards to using platform drivers.

Yes, I would suggest all new board start using it. If `barebox,allow-dummy;` then happens to work for you, can you prepare a patch?

2022-10-17 16:34 UTC, a3f commented
> Yes, I would suggest all new board start using it. If barebox,allow-dummy; then happens to work for you, can you prepare a patch?

Marco was faster: https://lore.barebox.org/barebox/20221017161818.333094-1-m.felsch@pengutronix.de/T/#t

2022-10-17 16:36 UTC, hcl-dr commented
I just got that - thanks!

17. okt. 2022 kl. 18:34 skrev Ahmad Fatoum ***@***.******@***.***>>:



Yes, I would suggest all new board start using it. If barebox,allow-dummy; then happens to work for you, can you prepare a patch?

Marco was faster: ***@***.***/T/#t

—
Reply to this email directly, view it on GitHub<https://github.com/saschahauer/barebox/pull/17#issuecomment-1281147427>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AONJNNBGKKNON6QQ5UCXLBTWDV523ANCNFSM6AAAAAARGLDS4A>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>