Imx8mm
barebox/barebox pull request #18
Opened 2023-01-03 06:05 UTC by js731ca

two fixes for imx8mm

2023-01-03 07:37 UTC, a3f requested changes
Usual contribution model is via mailing list. If you can use git-send-email, please submit your patches to the mailing list instead. This ensures more people will see your patches and comment on what might need changing.

Also, please adopt normal convention for commit messages, e.g.:

```
ARM: i.MX8M: imx8mm-evk: add support for new PCA9650 LPDDR4 variant

Existing EVK support is for LPDDR4 variant wit Rohm BD71837 PMIC,
but newer EVKs are fitted with PCA9450 on SoM. There's no upstream DT yet
.... etc.


S-o-b:
```

2023-01-03 07:37 UTC, a3f commented on arch/arm/mach-imx/imx8m.c
> +	    IS_ENABLED(CONFIG_FIRMWARE_IMX8MM_ATF)) {
As the function is common to all of i.MX8M, both IMX8MM and IMX8MQ defines are out of place. Either add a new CONFIG_FIRMWARE_IMX8M_ATF symbol that's select by both or replace with a `get_el() == 2` check.

2023-01-03 07:37 UTC, a3f commented on arch/arm/boards/nxp-imx8mm-evk/lowlevel.c
> +	pmic_configure(i2c, 0x25, pca9450_cfg, ARRAY_SIZE(pca9450_cfg));
Is your board the LPDDR4 or DDR4 variant? Anyhow, please keep old support in place. Check out i.MX8MN-EVK support for an example of how to detect whether to use Rohm or PCA PMIC at runtime.

2023-01-03 07:37 UTC, a3f commented on arch/arm/boards/nxp-imx8mp-evk/lowlevel.c
> +	imx8mp_early_clock_init();
Please split up into three patches: 8MM, 8MP,  8M -generic code.

2023-01-03 07:37 UTC, a3f commented on dts/src/arm64/freescale/imx8mm-evk.dts
> +
The whole `dts/` directory is imported wholesale from Linux and synced after every `-rc` and final release. Patches to these files should be submitted upstream to the SoC's Linux device tree maintainers.

When submitting it there, it should be a new file and not affect the old DT and it should have its own compatible. As an interim solution, you can add the DT to `arch/arm/dts` which contains the barebox DTs.

For more info, see: https://www.barebox.org/doc/latest/devicetree/index.html#barebox-device-trees

2023-01-11 04:21 UTC, js731ca commented on arch/arm/mach-imx/imx8m.c
> +	    IS_ENABLED(CONFIG_FIRMWARE_IMX8MM_ATF)) {
looking at firmware/Makefile - wich adds a per variant bl31.bin - i think it should be an || of all imx8m variants instead
'grep get_el' didn't turn up any matches - what did you have in mind there?

2023-01-11 04:27 UTC, js731ca commented
> Usual contribution model is via mailing list.

that's an "aaaaw, and there i was happy to find 'the' official github repository" with all it's niceties (webinterface, PR handling, ...)
should have read the readme more thoroughly - so i'll close this PR and push v2 to the ML?

2023-01-11 04:28 UTC, js731ca commented on dts/src/arm64/freescale/imx8mm-evk.dts
> +
as you probably noticed - patches are pushed (or tried to) to the linux kernel ML
i'll drop the added dts/patch here; wait for the kernel/dts sync

2023-01-11 06:45 UTC, a3f commented on arch/arm/mach-imx/imx8m.c
> +	    IS_ENABLED(CONFIG_FIRMWARE_IMX8MM_ATF)) {
> looking at firmware/Makefile - wich adds a per variant bl31.bin - i think it should be an || of all imx8m variants instead

That's equivalent to having all SoC-specific symbols select one symbol and check against that in code.

> 'grep -rniI get_el' didn't turn up any matches - what did you have in mind there?

Sorry, it's called `current_el()`

2023-01-11 06:47 UTC, a3f commented on dts/src/arm64/freescale/imx8mm-evk.dts
> +
You can for now add the evkb DT to `arch/arm/dts` in barebox and turn it into an `#include <arm64/freescale/imx8mm-evkb.dts>` once the changes make it into a kernel release that's imported into barebox.

2023-01-11 06:49 UTC, a3f commented
>  should have read the readme more thoroughly - so i'll close this PR and push v2 to the ML?

Sascha occasionally merged patches via Github for contributors that have problems sending unmangled mails, but it's not the norm. This is just a mirror. Let's continue on the mailing list. :)

2023-02-01 17:08 UTC, a3f commented
FTR, this is now resolved by https://github.com/saschahauer/barebox/commit/49b0c622eff312b52c26835d6361f025d16be16b, so this PR can be closed.

2023-02-01 21:30 UTC, closed without merging

2023-02-01 21:31 UTC, js731ca commented
Thanks! (-: