ARCH_IMX8M: Re-enable hidden features
barebox/barebox pull request #24
Opened 2023-07-12 09:01 UTC by hcl-dr

https://github.com/barebox/barebox/issues/23

IMX8M(P) supports functinality masked by
ARCH_IMX8MQ and corresponding is_cpu.. functions.
HABv4 goes for ARCH_IMX8M and PCIe for ARCH_IMX8MP as well

2023-07-12 09:10 UTC, a3f requested changes

2023-07-12 09:10 UTC, a3f commented on arch/arm/mach-imx/Kconfig
> +	depends on ARCH_IMX6 || ARCH_IMX8M
Yes, HAB didn't change, but the way SRAM events are read does: See https://lore.barebox.org/barebox/20230705171056.352794bb@drumknott/T/#md64f210fc6a8c9d19c798f2e28517420fc5f873f. Before that's merged, we shouldn't reenable the option just yet.

2023-07-12 09:10 UTC, a3f commented on drivers/pci/Kconfig
> +	select PCIE_DW
Duplicate line

2023-07-12 09:10 UTC, a3f commented on drivers/pci/Kconfig
> +	depends on ARCH_IMX6 || ARCH_IMX7 || ARCH_IMX8MQ || ARCH_IMX8MP
I don't think the i.MX8MQ driver is compatible with the i.MX8MP. The driver needs changes still and before these are done, it makes no sense to enable its selection.

2023-07-12 09:10 UTC, a3f commented on drivers/regulator/Kconfig
> +	depends on ARCH_IMX6 || ARCH_IMX8M
Do you actually have a system with a PFUZE PMIC powering an i.MX8M?

2023-07-12 09:59 UTC, hcl-dr commented on drivers/regulator/Kconfig
> +	depends on ARCH_IMX6 || ARCH_IMX8M
PCA9450 PFUZE variant on 3 systems.
Anyway, if it is relevant for a IMX8MQ it is likely relevant for IMX8M.
Otherwise it should probably be restricted to IMX6 family.
If the PFUZE driver does not support PCA9450 it is fine with me to leave it out for ARCH_IMX8M

2023-07-12 10:12 UTC, closed without merging

2023-07-17 09:56 UTC, a3f commented on drivers/regulator/Kconfig
> +	depends on ARCH_IMX6 || ARCH_IMX8M
PCA9450 is currently only configured in barebox prebootloader prior to DRAM setup. PFUZE driver in barebox proper doesn't work for PCA9450 and if support were to be added for it into barebox proper, it would be a separate driver like in Linux.

2024-01-22 14:32 UTC, a3f commented on arch/arm/mach-imx/Kconfig
> +	depends on ARCH_IMX6 || ARCH_IMX8M
FTR, v2023.11.0 was the first release with full i.MX8MP HABv4 support.

2024-01-22 14:33 UTC, a3f commented on drivers/regulator/Kconfig
> +	depends on ARCH_IMX6 || ARCH_IMX8M
FTR, v2023.12.0 has a simple PCA9450 driver, which could be extended if needed.